import { auth } from "@/auth";
import UnauthenticatedApp from "@/components/UnauthenticedApp";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={inter.className}>
      {session?.user ? <main>{children}</main> : <UnauthenticatedApp>{children}</UnauthenticatedApp>}
      </body>
    </html>
  );
}
